Updated the README with a section for how to create a new project.
STREGAsGate/Raylib pull request #8
Opened 2022-09-24 21:49 UTC by mgrider

I also added various links and had fun making the example project respond to mouse events. I really wanted to also delete the old Raylib README contents, but I figured you probably left it in there for a reason, so I didn't.

2022-09-25 20:00 UTC, STREGAsGate commented on README.md
>  .package(url: "https://github.com/STREGAsGate/Raylib.git", .branch("master"))
This format is deprecated as of Swift 5.6
A newly created package will need this format, so lets use that:
`.package(url: "https://github.com/STREGAsGate/Raylib.git", branch: "master")`

2022-09-25 20:00 UTC, STREGAsGate commented on README.md
> +        var ballPosition: Vector2 = .init(x: -100, y: -100)
Lets change this to:
`var ballPosition = Vector2(x: -100, y: -100)`

2022-09-25 20:01 UTC, STREGAsGate commented on README.md
> +$ mkdir My_Game
Let's change all instances of My_Game to MyGame. It's just cleaner because Swift is going to name everything after that folder.

2022-09-25 20:17 UTC, STREGAsGate commented on README.md
> +3. Find the `@main` struct in the Swift package and replace it (or its contents) with something like the following:
Let's simplify this:

3. Add the following to the `static func main()` in MyGame.swift.

```swift
    let screenWidth: Int32 = 800
    let screenHeight: Int32 = 450
     
    Raylib.initWindow(screenWidth, screenHeight, "MyGame")
    Raylib.setTargetFPS(30)
    let randomColors: [Color] = [.blue, .red, .green, .yellow, .darkBlue, .maroon, .magenta]
    var ballColor: Color = .maroon
    var ballPosition = Vector2(x: -100, y: -100)
    var previousBallPosition: Vector2
    while Raylib.windowShouldClose == false {
        // update
        previousBallPosition = ballPosition
        ballPosition = Raylib.getMousePosition()
            if Raylib.isMouseButtonDown(.left) {
                ballColor = randomColors.randomElement() ?? .black
            }
            let size = max(abs(ballPosition.x - previousBallPosition.x) + abs(ballPosition.y - previousBallPosition.y), 10)
            
            // draw
            Raylib.beginDrawing()
            Raylib.clearBackground(.rayWhite)
            Raylib.drawText("Hello, world!", 425, 25, 25, .darkGray)
            Raylib.drawCircleV(ballPosition, size, ballColor)
            Raylib.drawFPS(10, 10)
            Raylib.endDrawing()
        }
        Raylib.closeWindow()
```

2022-09-25 20:22 UTC, STREGAsGate commented on README.md
> +Below is the original [Raylib](https://github.com/raysan5/raylib) README.
Make this a separated heading

---
# Below is the original [Raylib](https://github.com/raysan5/raylib) README.


and delete:
---
 # Official Readme

2022-09-25 20:24 UTC, STREGAsGate commented on README.md
> +2. Edit the newly created `Package.swift` to add Raylib to the dependencies array:
make the number's bold by wrapping them in double `*`
`**2.**`
**2.**

2022-09-25 20:24 UTC, STREGAsGate commented on README.md
> +1. Create a Swift package for your project.
make the number's bold by wrapping them in double `*`
`**1.**`
**1.**

2022-09-25 20:27 UTC, STREGAsGate requested changes
Got a few changes for yah in the comments.

2022-09-28 06:06 UTC, mgrider commented
Alright, those all seem reasonable.

2022-09-28 06:19 UTC, merged

2022-09-28 06:19 UTC, STREGAsGate commented
Awesome. thanks for doing that 🙂